language: java


jdk:
  - oraclejdk7
  


after_success:
  -git tag -a build_%{build_number}

deploy: 
  provider: heroku
  api-key: "00d82953-3129-4cec-addb-a4c8a834664b"
  
  
before_install:
 - cd java
  
