language: java
 jdk:
 - oraclejdk8
 script:
  - mvn install -DskipTests=false
  - git log origin/master.. --stat
 after_success:
  - git tag -a build_%{build_number}
 deploy:
  provider: heroku
  api-key: "82544c97-bc53-4b59-98f3-d63973c62c51"
app: gerencia
